before/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "galleries#index"

  resources :galleries, except: [:edit, :update] do
    resources :artists, except: [:index, :show]
  end
end

before/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

before/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string
#  gallery_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ApplicationRecord
  belongs_to :gallery, counter_cache: true
end

before/app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id            :integer          not null, primary key
#  name          :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  artists_count :integer          default(0)
#

class Gallery < ApplicationRecord
  has_many :artists, dependent: :destroy
end

before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

before/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_gallery
  before_action :set_artist, only: [:edit, :update, :destroy]

  def new
    @artist = @gallery.artists.new
  end

  def edit
  end

  def create
    @artist = @gallery.artists.new(artist_params)

    if @artist.save
      redirect_to @gallery, notice: 'Artist was successfully created.'
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to @gallery, notice: 'Artist was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy

    redirect_to @gallery, notice: 'Artist was successfully destroyed.'
  end

  private

  def set_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end

  def set_artist
    @artist = @gallery.artists.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name)
  end
end

before/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  def index
    @galleries = Gallery.all
  end

  def show
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      redirect_to @gallery, notice: 'Gallery was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @gallery.destroy

    redirect_to galleries_url, notice: 'Gallery was successfully destroyed.'
  end

  private

  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  def gallery_params
    params.require(:gallery).permit(:name)
  end
end

before/app/helpers/application_helper.rb
module ApplicationHelper
end

before/app/helpers/artists_helper.rb
module ArtistsHelper
end

before/app/helpers/galleries_helper.rb
module GalleriesHelper
end

before/app/views/artists/_form.html.erb
<%= form_with(model: [artist.gallery, artist], local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %></br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

before/app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back to Gallery', gallery_artist_path(@gallery, @artist) %>

before/app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render "form", artist: @artist %>

<%= link_to "Back to Gallery", gallery_path(@gallery) %>

before/app/views/galleries/_form.html.erb
<%= form_with(model: gallery, local: true) do |form| %>
  <% if gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %></br>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

before/app/views/galleries/index.html.erb
<h1>Galleries</h1>

<% @galleries.each do |gallery| %>
  <div class="gallery">
    <h2><%= link_to gallery.name, gallery %></h2>
    Artists: <%= gallery.artists_count %>
  </div>
<% end %>

<p><%= link_to "New Gallery", new_gallery_path %></p>

before/app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Back', galleries_path %>

before/app/views/galleries/show.html.erb
<h1><%= @gallery.name %></h1>

<div id="artists">
  <% @gallery.artists.each do |artist| %>
    <div class="artist">
      <div class="image_placeholder"></div>
      <div class="name"><%= artist.name %></div>
      <div class="actions">
        <%= link_to "edit", edit_gallery_artist_path(@gallery, artist) %> |
        <%= link_to "remove", [@gallery, artist], confirm: "Are you sure?", method: :delete %>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

<p>
  <%= link_to "Add an Artist", new_gallery_artist_path(@gallery) %> |
  <%= link_to "Remove Gallery", @gallery, confirm: "Are you sure?", method: :delete %> |
  <%= link_to "View Galleries", galleries_path %>
</p>

before/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Active Storage Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>